---
name: Metrics
run-name: Updating metrics on ${{github.repository_owner}}'s profile.
concurrency: main
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Github metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.PROFILE_METRICS }}
          filename: .github/metrics.svg
          template: classic
          base: header, activity, community, repositories, metadata
          base_hireable: yes
          config_timezone: Europe/London
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_stars: yes
          plugin_stars_limit: 4