---
name: Metrics
run-name: Updating metrics on ${{github.repository_owner}}'s profile.
concurrency: main
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Github metrics
        uses: lowlighter/metrics@latest
        with:
          base_hireable: true
          token: ${{ secrets.PROFILE_METRICS }}
          filename: .github/metrics.svg
